# Generated by Django 3.2 on 2022-03-31 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apodphoto',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 20, 57, 2, 69387, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apodphoto',
            name='explanation',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
