# Generated by Django 3.2 on 2022-04-04 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0003_apodphoto_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apodphoto',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apodposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
