# Generated by Django 3.2 on 2022-04-07 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_marsphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marsphoto',
            name='media',
        ),
        migrations.AddField(
            model_name='marsphoto',
            name='camera_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marsphoto',
            name='earth_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marsphoto',
            name='rover',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marsphoto',
            name='sol',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
